### PR TITLE
add Tellor Module

### PR DESCRIPTION
**Pull request by QuintusTheFifth**

### CODE REVIEW

**Comment by auryn-macmillan** [comment]
@QuintusTheFifth, did you build a Zodiac-style logo for this mod?

**Comment by QuintusTheFifth** [comment]
I did not, just used an existing one as a placeholder. How do I create one?

**Comment by samepant** [comment]
@QuintusTheFifth how does this look? If this works, i'll add it to our component library and make a pr on this branch to include it.
logo_zodiac_tellor@2x

**Comment by QuintusTheFifth** [comment]
Yes, looks great. Thanks!

**Comment by samepant** [comment]
@QuintusTheFifth I opened a PR into your fork here: https://github.com/QuintusTheFifth/zodiac-safe-app/pull/2

If it looks alright, merge it and we can get this one merged.

**Comment by QuintusTheFifth** [comment]
@samepant LGTM

**Pull request merged**
