### PR TITLE
Create Monitoring and Review section UI

### LINKED ISSUE #69: [Reality Module - Improvements] - Monitoring Step UI
**Is your feature request related to a problem? Please describe.**
We need to improve the Reality Module UX

**Describe the solution you'd like**
After this, issue #68, we're going to continue with Configurate Monitoring UI

- [x] Create Monitoring Service Section
- [x] Create Monitoring Configuration Section

**Additional context**
To complete this task, we need to follow the design made by @cedricwaxwing
- https://www.figma.com/file/Ozca9QH0SKyrCRSZOR6Ri0/Reality-Module?node-id=45%3A3936
- https://www.figma.com/file/Ozca9QH0SKyrCRSZOR6Ri0/Reality-Module?node-id=49%3A1440

### LINKED ISSUE #70: [Reality Module - Improvements] - Review Step UI
**Is your feature request related to a problem? Please describe.**
We need to improve the Reality Module UX

**Describe the solution you'd like**
After this, issue #69, we're going to continue with Review UI

- [ ]  Create Review UI Section

**Additional context**
To complete this task, we need to follow the design made by @cedricwaxwing

- https://www.figma.com/file/Ozca9QH0SKyrCRSZOR6Ri0/Reality-Module?node-id=45%3A4423

### PR DESCRIPTION
**Pull request by juliopavila**
closed #69 
closed #70 

Monitoring UI
image
image

Review UI
image
image

### CODE REVIEW

**Review by manboy-eth — CHANGES_REQUESTED** [review]
Nice work.

**Feedback**
- For some reason the dropdown menus look wired, they span the whole window:
Screenshot 2022-08-08 at 10 59 19
Screenshot 2022-08-08 at 10 59 04
- the review next button should be like Figma ("Submit"):
Screenshot 2022-08-08 at 11 02 01

**Comment by juliopavila** [comment]
> Nice work.
> 
> **Feedback**
> 
> * For some reason the dropdown menus look wired, they span the whole window:
> 
> Screenshot 2022-08-08 at 10 59 19
> 
> Screenshot 2022-08-08 at 10 59 04
> 
> - the review next button should be like Figma ("Submit"):
> Screenshot 2022-08-08 at 11 02 01

Done
image
image

**Comment by manboy-eth** [comment]
> > Nice work.
> > **Feedback**
> > 
> > * For some reason the dropdown menus look wired, they span the whole window:
> > 
> > Screenshot 2022-08-08 at 10 59 19
> > Screenshot 2022-08-08 at 10 59 04
> > 
> > * the review next button should be like Figma ("Submit"):
> > 
> > Screenshot 2022-08-08 at 11 02 01
> 
> Done image image

Hmm, I am still having the problem with the dropdown. Merging anyway, we can fix it later ✌️

Everything else: 👏 👏

**Review by manboy-eth — APPROVED** [review]
Hmm, I am still having the problem with the dropdown. Merging anyway, we can fix it later ✌️

Everything else: 👏 👏

**Pull request merged**
